### ISSUE TITLE
koishi-plugin-latex-image 停止维护

### ISSUE THREAD

**Issue by TTsdzb** [Anillc/koinix#1]
我是插件作者，插件功能与一个更早的官方插件 `tex` 冲突了，而且比我的实现更好。请使用那个插件。

**Comment by Anillc** [comment]
这个仓库会将所有 koishi 插件加入依赖，并没有实际使用该插件，所以没有问题。

**Comment by TTsdzb** [comment]
> 这个仓库会将所有 koishi 插件加入依赖，并没有实际使用该插件，所以没有问题。

好的，不过现在这个插件已经设为deprecated了，按照koishi的插件规范，它将不再在插件市场中显示了。你可能需要把它移除掉。
